TYPE_IMAGES =          'images'
TYPE_DESIGN =          'design'
TYPE_PYTHON =          'python'
TYPE_PRESENTATION =    'presentation'
TYPE_SCRATCH =         'scratch'
TYPE_WEBSITE =         'website'
TYPE_GAMEDESIGN =      'gamedesign'
TYPE_UNITY =           'unity'
TYPE_VIDEO =           'video'
TYPE_VSCODE =          'vscode'

RELATIONSHIP_FOLLOW =  'follow'
RELATIONSHIP_FRIEND =  'friend'

SHARING_MODE_PRIVATE = 'private'
SHARING_MODE_GROUP =   'group'
SHARING_MODE_PUBLIC =  'universe'

REACTION_LOVE =        'love'
REACTION_LIKE =        'like'
REACTION_FIRE =        'fire'

SORT_LATEST =          'id'
SORT_CREATED_AT =      'created_at'
SORT_COMMENT_COUNT =   'comments_count'
SORT_BEST =            'best'

EMOJI_ANGRY =          ':angry'
EMOJI_FIRE =           ':fire'
EMOJI_HEART =          ':heart'
EMOJI_LIKE =           ':like'
EMOJI_REASONING =      ':reasoning'
EMOJI_SAD =            ':sad'
EMOJI_WOW =            ':wow'

TRENDS_DAY =           'day'
TRENDS_WEEK =          'week'
TRENDS_MONTH =         'month'